using System.Linq.Expressions;
using Microsoft.AspNetCore.Html;
using Telefrag.Common;

namespace Silo.DbModel.Meta;

public class MetaDb
{
}

/// <summary>
/// Defines a meta-tye.
/// </summary>
public record MvType(
    int         Id,
    string      Name,
    string      DisplayName,
    MvTypeFlags Flags);

/// <summary>
/// Defines a relationship (inheritance or inclusion) between two meta-types.
/// </summary>
public record MvTypeHierarchy(
    int          Id,
    MvType       Subject,
    MvType       Target,
    TypeRelation Relation);

public enum TypeRelation
{
    /// <summary>
    /// The subject type inherits the target (base) type
    /// </summary>
    Inheritance,

    /// <summary>
    /// The subject type includes the target (auxiliary) type
    /// </summary>
    Auxiliary
}

/// <summary>
/// Defines a metaverse type (meta-type) attribute
/// </summary>
/// <param name="Id">Primary key</param>
/// <param name="Name">Unique short name for the field</param>
/// <param name="DisplayName">Human-readable renamable name</param>
/// <param name="Type">Type name of the .NET data type</param>
/// <param name="Syntax">Name of the syntax used</param>
/// <param name="DefaultValue">Optional default value</param>
/// <param name="CombinatorType">Type name of the combinator used to combine values</param>
/// <param name="Flags">Attribute-level flags</param>
public record MvAttribute(
    int              Id,
    string           Name,
    string           DisplayName,
    string           Type,
    int?             Syntax,
    string?          DefaultValue,
    string           CombinatorType,
    MvAttributeFlags Flags);

/// <summary>
/// Values used to indicate how a metaverse type should function
/// </summary>
public enum MvTypeFlags
{
    /// <summary>
    /// Default behavior
    /// </summary>
    None,

    /// <summary>
    /// The type provides supplemental fields for other unrelated types which
    /// include a reference to this type.
    /// </summary>
    Auxiliary = 1,
}

/// <summary>
/// Flags indicating how a metaverse attribute should be treated
/// </summary>
public enum MvAttributeFlags
{
    /// <summary>
    /// Default behavior
    /// </summary>
    None = 0,

    /// <summary>
    /// The field is nullable
    /// </summary>
    Nullable = 1,

    /// <summary>
    /// The field is multivalued
    /// </summary>
    Multivalue = 2,

    /// <summary>
    /// The field should be indexed
    /// </summary>
    Indexed = 4,

    /// <summary>
    /// The field is included in ANR
    /// </summary>
    Anr = 8,

    /// <summary>
    /// The field is the type's primary key
    /// </summary>
    Key = 0x10
}

public record MvObj(
    long     Id,
    MvType   Type,
    string   Key,
    DateTime Created,
    DateTime Modified,
    Uri      LocalUri,
    [property: Newtonsoft.Json.JsonExtensionData]
    Dictionary<string, object> FieldValues)
{
}

/*
 *
 * For every connected object, the engine tracks up to three representations of its state:

Import Hologram: What the external connected system actually reported during the last
                Delta Import or Full Import.

Pending Export Hologram (Delta/Unconfirmed):
                The desired state generated by Metaverse outbound sync rules during
                the last Delta Synchronization or Full Synchronization.

Base / Export Hologram:
                The state the sync engine believes the target system has accepted
                after an Export run, prior to a subsequent import confirming it.
 */

public record Connector(
    long      Id,
    MvObj     MvObj,
    string    World,
    string    WorldType,
    string    Key,
    string    AbsolutePath,
    LinkedVia LinkedVia,
    DateTime? LinkedAt);

public enum LinkedVia
{
    /// <summary>
    /// The links origin is not defined or available
    /// </summary>
    None,

    /// <summary>
    /// The link was created manually
    /// </summary>
    Manual,

    /// <summary>
    /// The link was created via JOIN rules (e.g. World to existing Metaverse)
    /// </summary>
    Join,

    /// <summary>
    /// Ths link was created via provisioning (e.g. this connector created the World object).
    /// </summary>
    Provision,

    /// <summary>
    /// The link was created via Projection rules (e.g. this is the first connector on the MV object)
    /// </summary>
    Projection
}

public record ConnectorPending(
    long           Id,
    Connector      Connector,
    PendingDelete? Delete,
    PendingUpdate? Update,
    PendingCreate? Create,
    int            Failures,
    string         LastFailure,
    DateTime?      LastFailed);

public enum MvObjFlags
{
    None      = 0,
    Tombstone = 1
}