<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Trace" Version="4.0.0" />
    <PackageReference Include="Telefrag.Common" Version="2026.9.11.372" />
    <PackageReference Include="Telerik.Documents.Core" Version="2025.3.806" />
    <PackageReference Include="Telerik.Documents.Flow" Version="2025.3.806" />
    <PackageReference Include="Telerik.Documents.Spreadsheet" Version="2025.3.806" />
    <PackageReference Include="Telerik.Documents.Spreadsheet.FormatProviders.Xls" Version="2025.3.806" />
    <PackageReference Include="Telerik.Pivot.Core" Version="0.1.6" />
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="2025.3.813" />
    <PackageReference Include="Telerik.Windows.Controls.Diagrams.Extensions.for.Wpf.Xaml" Version="2025.3.813" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Providers\Uri\" />
    <Folder Include="Subconnectors\" />
    <Folder Include="ViewModel\Features\" />
  </ItemGroup>



</Project>
